# Generated by Django 2.1.7 on 2019-05-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'breakdown_course',
            },
        ),
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('user_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Course list',
                'verbose_name_plural': 'Course lists',
                'db_table': 'course_list',
            },
        ),
        migrations.CreateModel(
            name='GroupBy',
            fields=[
                ('grouping_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_by', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Group by',
                'verbose_name_plural': 'Group by',
                'db_table': 'group_by',
            },
        ),
        migrations.CreateModel(
            name='GroupSurveyList',
            fields=[
                ('survey_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Group survey list',
                'verbose_name_plural': 'Group survey lists',
                'db_table': 'group_survey_list',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('poll_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic1', models.IntegerField()),
                ('topic2', models.IntegerField()),
                ('topic3', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
                ('survey_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
                'db_table': 'poll',
            },
        ),
        migrations.CreateModel(
            name='StudentTeamList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Student team list',
                'verbose_name_plural': 'Student team lists',
                'db_table': 'student_team_list',
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Study Group',
                'verbose_name_plural': 'Study Groups',
                'db_table': 'study_group',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('survey_name', models.CharField(max_length=20)),
                ('is_formed', models.BooleanField(default=True)),
                ('due_date', models.DateTimeField()),
                ('course', models.CharField(max_length=64, null=True)),
                ('course_id', models.IntegerField()),
                ('min_student', models.PositiveIntegerField(default=4)),
                ('max_student', models.PositiveIntegerField(default=6)),
                ('group_by', models.IntegerField(choices=[(3, 'Group'), (2, 'Course'), (1, 'TA')])),
                ('description', models.CharField(max_length=128)),
                ('additional_info', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
                'db_table': 'survey',
            },
        ),
        migrations.CreateModel(
            name='SurveyTopicList',
            fields=[
                ('topic_id', models.IntegerField()),
                ('survey_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Survey topic list',
                'verbose_name_plural': 'Survey topic lists',
                'db_table': 'survey_topic_list',
            },
        ),
        migrations.CreateModel(
            name='TaSurveyList',
            fields=[
                ('user_id', models.IntegerField()),
                ('survey_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'TA survey list',
                'verbose_name_plural': 'TA Survey lists',
                'db_table': 'ta_survey_list',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('topic_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('additional_info', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'db_table': 'topic',
            },
        ),
        migrations.CreateModel(
            name='UserGroupList',
            fields=[
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'User group list',
                'verbose_name_plural': 'User group lists',
                'db_table': 'user_group_list',
            },
        ),
        migrations.CreateModel(
            name='UserTopicList',
            fields=[
                ('user_id', models.IntegerField()),
                ('topic_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'User topic list',
                'verbose_name_plural': 'User topic lists',
                'db_table': 'user_topic_list',
            },
        ),
    ]
