# Generated by Django 2.1.7 on 2019-05-01 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'breakdown_course',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('poll_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic1', models.IntegerField()),
                ('topic2', models.IntegerField()),
                ('topic3', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
                ('survey_id', models.IntegerField()),
                ('language1', models.IntegerField()),
                ('language2', models.IntegerField()),
                ('language3', models.IntegerField()),
                ('group_by', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
                'db_table': 'poll',
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Study Group',
                'verbose_name_plural': 'Study Groups',
                'db_table': 'study_group',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('survey_name', models.CharField(max_length=20)),
                ('is_formed', models.BooleanField(default=True)),
                ('due_date', models.DateTimeField()),
                ('course', models.CharField(max_length=64, null=True)),
                ('course_id', models.IntegerField()),
                ('min_student', models.PositiveIntegerField(default=4)),
                ('max_student', models.PositiveIntegerField(default=6)),
                ('group_by', models.IntegerField(choices=[(3, 'Group'), (2, 'Course'), (1, 'TA')])),
                ('description', models.CharField(max_length=128)),
                ('additional_info', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
                'db_table': 'survey',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('additional_info', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'db_table': 'topic',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdown.Topic'),
        ),
    ]
