# Generated by Django 2.1.7 on 2019-04-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'breakdown_course',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=20)),
                ('is_formed', models.BooleanField(default=True)),
                ('due_date', models.DateTimeField()),
                ('course_id', models.IntegerField()),
                ('min_student', models.PositiveIntegerField(default=4)),
                ('max_student', models.PositiveIntegerField(default=6)),
                ('group_by', models.IntegerField(choices=[(3, 'Group'), (2, 'Course'), (1, 'TA')])),
                ('description', models.CharField(max_length=128)),
                ('additional_info', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
                'db_table': 'project',
            },
        ),
    ]
