# Generated by Django 2.1.7 on 2019-04-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='course',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
