# Generated by Django 2.1.7 on 2019-03-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
