# Generated by Django 2.1.7 on 2019-04-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0002_survey_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProjectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='survey',
            name='course',
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
