# Generated by Django 2.1.7 on 2019-04-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0003_auto_20190427_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupProjectList',
        ),
        migrations.AddField(
            model_name='survey',
            name='course',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
