# Generated by Django 2.1.7 on 2019-04-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0003_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('surname',)},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='surname',
        ),
    ]
