# Generated by Django 2.1.7 on 2019-04-12 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0006_auto_20190404_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
