# Generated by Django 2.1.7 on 2019-04-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0007_auto_20190412_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=20)),
                ('is_open', models.BooleanField(default=True)),
                ('due_date', models.DateTimeField()),
                ('course_id', models.IntegerField()),
                ('min_student', models.PositiveIntegerField(default=4)),
                ('max_student', models.PositiveIntegerField(default=6)),
                ('group_by', models.IntegerField(choices=[(3, 'Group'), (2, 'Course'), (1, 'TA')])),
                ('description', models.CharField(max_length=128)),
                ('additional_info', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
                'db_table': 'breakdown_project',
            },
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
