# Generated by Django 2.1.7 on 2019-04-14 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0008_auto_20190414_2308'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='breakdown_course',
        ),
        migrations.AlterModelTable(
            name='survey',
            table='project',
        ),
    ]
